Repository Babyjawz/nymphs-savage-world, pull requests merged in 2025-08, with the labels that each got.

#3 Update README.md
  README.md
Labels: documentation

#10 Update README.md
  README.md
Labels: documentation, tweak

#16 Update labels.yml
  .github/labels.yml
Labels: tweak

#19 Update file-check.yml
  .github/workflows/file-check.yml
Labels: 🛠️ tweak

#20 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 📝 docs

#22 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 📝 docs

#23 Update pull_request_template.md
  .github/pull_request_template.md
Labels: 🛠️ tweak

#26 Update README.md
  README.md
Labels: 📝 docs

#29 Create elsify.md
  docs/notes/elsify.md
Labels: 🔧 other

#31 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 📝 docs

#38 Delete docs/notes/lildawn_notes.md
  docs/notes/lildawn_notes.md
Labels: 🔧 other

#41 Update README.md
  README.md
Labels: 🔧 other

#45 Delete docs directory
  docs/notes/LilDawn_Notes.md
  docs/notes/elsify.md
Labels: 🔧 other

#47 Update README.md
  Submissions/README.md
Labels: 🛠️ tweak

#48 Update README.md
  Submissions/README.md
Labels: 🛠️ tweak

#49 Update CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: 📝 docs

#51 Create Hacker.md
  Hacker.md
Labels: 🔧 other

#55 Nyxs Witchy Stitches
  Submissions/rauty79/NWS Changelog.md
  Submissions/rauty79/README.md
Labels: 🔧 other

#58 NWS Changelog.md
  Submissions/rauty79/NWS Changelog.md
Labels: 🔧 other

#60 Assets for PGpatcher guide
  .github/assets/1.png
  .github/assets/2.png
  .github/assets/3.png
  .github/assets/4.png
  .github/assets/5.png
Labels: 🔧 other
